set(_CATKIN_CURRENT_PACKAGE "parsian_agent")
set(parsian_agent_VERSION "0.0.0")
set(parsian_agent_MAINTAINER "Mohammad Mahdi Rahimi <mohammadmahdi76@gmail.com>")
set(parsian_agent_PACKAGE_FORMAT "1")
set(parsian_agent_BUILD_DEPENDS "dynamic_reconfigure" "nodelet" "parsian_msgs" "parsian_util" "roscpp" "rospy" "std_msgs" "roslint")
set(parsian_agent_BUILD_EXPORT_DEPENDS "dynamic_reconfigure" "nodelet" "parsian_msgs" "parsian_util" "roscpp" "rospy" "std_msgs")
set(parsian_agent_BUILDTOOL_DEPENDS "catkin")
set(parsian_agent_BUILDTOOL_EXPORT_DEPENDS )
set(parsian_agent_EXEC_DEPENDS "dynamic_reconfigure" "nodelet" "parsian_msgs" "parsian_util" "roscpp" "rospy" "std_msgs")
set(parsian_agent_RUN_DEPENDS "dynamic_reconfigure" "nodelet" "parsian_msgs" "parsian_util" "roscpp" "rospy" "std_msgs")
set(parsian_agent_TEST_DEPENDS )
set(parsian_agent_DOC_DEPENDS )
set(parsian_agent_URL_WEBSITE "")
set(parsian_agent_URL_BUGTRACKER "")
set(parsian_agent_URL_REPOSITORY "")
set(parsian_agent_DEPRECATED "")